import { createFont, createShorthands, createTamagui, createTokens } from '@tamagui/core';
import { designFoundation } from './foundation';

const bodyFont = createFont({
  family: designFoundation.fonts.body,
  size: {
    1: 12,
    2: 14,
    3: 16,
    4: 18,
    5: 20,
    6: 24,
    7: 32,
    8: 44,
    9: 56,
  },
  lineHeight: {
    1: 18,
    2: 20,
    3: 24,
    4: 28,
    5: 30,
    6: 34,
    7: 40,
    8: 52,
    9: 64,
  },
  weight: {
    1: '400',
    2: '500',
    3: '600',
    4: '700',
    5: '800',
  },
  letterSpacing: {
    7: -0.8,
    8: -1.2,
    9: -1.8,
  },
});

const headingFont = createFont({
  family: designFoundation.fonts.heading,
  size: {
    1: 16,
    2: 18,
    3: 20,
    4: 24,
    5: 30,
    6: 36,
    7: 44,
    8: 56,
    9: 68,
  },
  lineHeight: {
    1: 20,
    2: 22,
    3: 24,
    4: 28,
    5: 34,
    6: 40,
    7: 48,
    8: 60,
    9: 72,
  },
  weight: {
    1: '700',
    2: '700',
    3: '700',
    4: '800',
    5: '800',
  },
  letterSpacing: {
    4: -0.4,
    5: -0.8,
    6: -1,
    7: -1.2,
    8: -1.5,
    9: -1.8,
  },
});

const tokens = createTokens({
  color: {
    background: designFoundation.colors.background,
    backgroundSoft: designFoundation.colors.backgroundSoft,
    surface: designFoundation.colors.surface,
    surfaceStrong: designFoundation.colors.surfaceStrong,
    surfaceTint: designFoundation.colors.surfaceTint,
    border: designFoundation.colors.border,
    borderStrong: designFoundation.colors.borderStrong,
    text: designFoundation.colors.text,
    textMuted: designFoundation.colors.textMuted,
    brand: designFoundation.colors.brand,
    brandHover: designFoundation.colors.brandHover,
    brandSoft: designFoundation.colors.brandSoft,
    highlight: designFoundation.colors.highlight,
    highlightSoft: designFoundation.colors.highlightSoft,
    success: designFoundation.colors.success,
    warning: designFoundation.colors.warning,
  },
  space: {
    0: 0,
    1: 4,
    2: 8,
    3: 12,
    4: 16,
    5: 20,
    6: 24,
    7: 32,
    8: 48,
    9: 64,
    10: 80,
  },
  size: {
    0: 0,
    1: 12,
    2: 14,
    3: 16,
    4: 18,
    5: 20,
    6: 24,
    7: 32,
    8: 44,
    9: 56,
  },
  radius: {
    0: 0,
    1: 12,
    2: 14,
    3: 18,
    4: 20,
    5: 28,
    6: 999,
  },
  zIndex: {
    0: 0,
    1: 10,
    2: 20,
    3: 30,
    4: 40,
  },
});

const shorthands = createShorthands({
  ai: 'alignItems',
  bg: 'backgroundColor',
  boc: 'borderColor',
  br: 'borderRadius',
  bw: 'borderWidth',
  fd: 'flexDirection',
  fs: 'fontSize',
  fw: 'fontWeight',
  gap: 'gap',
  jc: 'justifyContent',
  lh: 'lineHeight',
  m: 'margin',
  mb: 'marginBottom',
  mt: 'marginTop',
  mx: 'marginHorizontal',
  my: 'marginVertical',
  p: 'padding',
  pb: 'paddingBottom',
  pt: 'paddingTop',
  px: 'paddingHorizontal',
  py: 'paddingVertical',
});

const config = createTamagui({
  tokens,
  shorthands,
  fonts: {
    body: bodyFont,
    heading: headingFont,
  },
  themes: {
    light: {
      background: designFoundation.colors.background,
      backgroundSoft: designFoundation.colors.backgroundSoft,
      surface: designFoundation.colors.surface,
      surfaceStrong: designFoundation.colors.surfaceStrong,
      surfaceTint: designFoundation.colors.surfaceTint,
      border: designFoundation.colors.border,
      borderStrong: designFoundation.colors.borderStrong,
      color: designFoundation.colors.text,
      colorMuted: designFoundation.colors.textMuted,
      primary: designFoundation.colors.brand,
      primaryHover: designFoundation.colors.brandHover,
      primarySoft: designFoundation.colors.brandSoft,
      primaryForeground: designFoundation.colors.text,
      accent: designFoundation.colors.highlight,
      accentSoft: designFoundation.colors.highlightSoft,
      success: designFoundation.colors.success,
      warning: designFoundation.colors.warning,
    },
  },
  media: {
    sm: { maxWidth: 720 },
    md: { maxWidth: 980 },
  },
  settings: {
    defaultFont: 'body',
  },
});

export type AppTamaguiConfig = typeof config;
export default config;
